return {
["ContentCreatorsCode2.5!"] = {
        Rewards = {
				Coins = 100_000,
				Rerolls = 50,
				RelicRerolls = 20,
				StatRerolls = 25,
				Locks = 15,
				Items = {
					SecretEtherealizationShard = 1,
				},
        },
        CC_Code = true,
        Expiration = os.time({
            year = 2026,
            month = 5,
            day = 10,
            min = 0,
            hour = 16,
            sec = 0,
        })
    },

["Update2.5!"] = {
        Rewards = {
				Rerolls = 30,
				RelicRerolls = 25,
				Gems = 5000,
				Coins = 30_000,
        },
        Expiration = os.time({
            year = 2026,
            month = 5,
            day = 2,
            min = 0,
            hour = 20,
            sec = 0,
        })
    },
["ShadowMonarch!"] = {
        Rewards = {
				Rerolls = 20,
				RelicRerolls = 5,
				StatRerolls = 20,
				Locks = 10,
				Gems = 2000,
				Coins = 20_000,
        },
		LevelRequirement = 15,
        Expiration = os.time({
            year = 2026,
            month = 5,
            day = 7,
            min = 0,
            hour = 20,
            sec = 0,
        })
    },
["CursedEnergy!"] = {
        Rewards = {
				Rerolls = 100,
				Gems = 5000,
				Coins = 100_000,
        },
		LevelRequirement = 30,
        Expiration = os.time({
            year = 2026,
            month = 5,
            day = 1,
            min = 0,
            hour = 20,
            sec = 0,
        })
    },
["Srry2.5Delay!"] = {
        Rewards = {
				Rerolls = 100,
        },
        Expiration = os.time({
            year = 2026,
            month = 4,
            day = 30,
            min = 0,
            hour = 20,
            sec = 0,
        })
    },

["TheFinalReveal!"] = {
        Rewards = {
				Coins = 30000,
				RelicRerolls = 15,
				Rerolls = 40,
				StatRerolls = 25
        },
        Expiration = os.time({
            year = 2026,
            month = 5,
            day = 1,
            min = 0,
            hour = 20,
            sec = 0,
        })
    },

["FinalReveals!"] = {
        Rewards = {
				Gems = 15000,
				Items = {
					MythicEtherealizationShard = 6,
					SecretEtherealizationShard = 3,
					ExclusiveEtherealizationShard = 3,
				},
        },
        Expiration = os.time({
            year = 2026,
            month = 4,
            day = 27,
            min = 0,
            hour = 20,
            sec = 0,
        })
    },
["1KFollowersUTDXTiktok!"] = {
        Rewards = {
				Rerolls = 100,
        },
        Expiration = os.time({
            year = 2026,
            month = 4,
            day = 27,
            min = 0,
            hour = 20,
            sec = 0,
        })
    },
["SailorBoost!"] = {
        Rewards = {
				Rerolls = 30,
				Items = {
					UnrivaledFragment1 = 1,
					UnrivaledFragment2 = 1,
				},
        },
        Expiration = os.time({
            year = 2026,
            month = 4,
            day = 27,
            min = 0,
            hour = 16,
            sec = 0,
        })
    },

["CoinsForEveryone!"] = {
        Rewards = {
				Coins = 100_000,
				YenCrates = 5,
        },
        Expiration = os.time({
            year = 2026,
            month = 4,
            day = 25,
            min = 0,
            hour = 16,
            sec = 0,
        })
    },

["CC_AntKing!"] = {
        Rewards = {
				Coins = 115_000,
				Rerolls = 65,
				RelicRerolls = 15,
				StatRerolls = 15,
				Locks = 25,
				YenCrates = 5,
        },
        CC_Code = true,
        Expiration = os.time({
            year = 2026,
            month = 5,
            day = 10,
            min = 0,
            hour = 16,
            sec = 0,
        })
    },
["ThankYouBeruMuch!"] = {
        Rewards = {
				Rerolls = 25,		
				RelicRerolls = 10,
				Gems = 5000,
        },
		LevelRequirement = 10,
        Expiration = os.time({
            year = 2026,
            month = 4,
            day = 24,
            min = 0,
            hour = 16,
            sec = 0,
        })
    },
["Update2.25!"] = {
        Rewards = {
				Rerolls = 30,		
				RelicRerolls = 25,
				Gems = 5000,
				Coins = 30_000,
        },
        Expiration = os.time({
            year = 2026,
            month = 4,
            day = 26,
            min = 0,
            hour = 16,
            sec = 0,
        })
    },

["2.25Patch!"] = {
        Rewards = {
				Gems = 5000,
				Rerolls = 40,
				RelicRerolls = 25,
        },
		LevelRequirement = 0,
        Expiration = os.time({
            year = 2026,
            month = 4,
            day = 28,
            min = 0,
            hour = 5,
            sec = 0,
        })
    },
["TheShadowMonarchIsArrivingSoon!"] = {
        Rewards = {
				Rerolls = 20,		
				RelicRerolls = 5,
				StatRerolls = 20,
				Locks = 10,
				Gems = 2000,
				Coins = 20_000,
        },
		LevelRequirement = 15,
        Expiration = os.time({
            year = 2026,
            month = 4,
            day = 26,
            min = 0,
            hour = 16,
            sec = 0,
        })
    },
["MiniUpdate2.25Sunday!"] = {
        Rewards = {
				Rerolls = 50,		
				RelicRerolls = 20,
				Gems = 5000,
        },
        Expiration = os.time({
            year = 2026,
            month = 4,
            day = 25,
            min = 0,
            hour = 16,
            sec = 0,
        })
    },
["TheAntIsland!"] = {
        Rewards = {
				Rerolls = 15,		
				Gems = 2500,
        },
        Expiration = os.time({
            year = 2026,
            month = 4,
            day = 20,
            min = 0,
            hour = 16,
            sec = 0,
        })
    },
["ThankYouForUTDX!"] = {
        Rewards = {
				Rerolls = 50,		
				RelicRerolls = 50,
				Gems = 10000,
        },
        Expiration = os.time({
            year = 2026,
            month = 4,
            day = 16,
            min = 0,
            hour = 20,
            sec = 0,
        })
    },
["WeLoveRerolls!"] = {
        Rewards = {
				Rerolls = 100,		
        },
        Expiration = os.time({
            year = 2026,
            month = 4,
            day = 18,
            min = 0,
            hour = 20,
            sec = 0,
        })
    },
["WeLoveDragonSlayer!"] = {
        Rewards = {
				Gems = 10000,
				Rerolls = 25,
				Units = {
					Stark = 1,
				},
				
        },
        Expiration = os.time({
            year = 2026,
            month = 4,
            day = 21,
            min = 0,
            hour = 20,
            sec = 0,
        })
    },
["ContentCreatorsCode2.0!"] = {
        Rewards = {
				Gold = 100_000,
				Rerolls = 50,
				RelicRerolls = 20,
				StatRerolls = 25,
				Locks = 15,
				Items = {
					SecretEtherealizationShard = 1,
				},
        },
        CC_Code = true,
        Expiration = os.time({
            year = 2026,
            month = 4,
            day = 26,
            min = 0,
            hour = 16,
            sec = 0,
        })
    },
["NinjaMaintenance"] = {
        Rewards = {
				Gems = 5000,
				Rerolls = 50,
				StatRerolls = 25,
				RelicRerolls = 25,
				Units = {
					Apollo = 1,
				},
				
        },
        Expiration = os.time({
            year = 2026,
            month = 4,
            day = 13,
            min = 0,
            hour = 20,
            sec = 0,
        })
    },

["2.0Patch!"] = {
        Rewards = {
				Gems = 5000,
				Rerolls = 25,
				RelicRerolls = 10,
        },
		LevelRequirement = 0,
        Expiration = os.time({
            year = 2026,
            month = 4,
            day = 20,
            min = 0,
            hour = 16,
            sec = 0,
        })
    },

["Update2.0!"] = {
        Rewards = {
				Coins = 50_000,
				Rerolls = 20,
				RelicRerolls = 10,
				StatRerolls = 30,
				Locks = 15,
        },
        Expiration = os.time({
            year = 2026,
            month = 4,
            day = 20,
            min = 0,
            hour = 16,
            sec = 0,
        })
    },
["WeLoveFern!"] = {
        Rewards = {
				Rerolls = 50,
				StatRerolls = 25,
				Units = {
					Fern = 1,
				},
				Items = {
					MageStaff = 1,
					UniversalFragment = 2,
					PhantomFragment = 4,
					PetalFragment = 6,
				},
        },
		LevelRequirement = 0,
        Expiration = os.time({
            year = 2026,
            month = 4,
            day = 20,
            min = 0,
            hour = 17,
            sec = 0,
        })
    },
["WeLoveUlquiorra!"] = {
        Rewards = {
				Rerolls = 50,
				Units = {
					["Ulquiorra:shiny:evolved"] = 1,
				},
        },
		LevelRequirement = 0,
        Expiration = os.time({
            year = 2026,
            month = 4,
            day = 28,
            min = 0,
            hour = 17,
            sec = 0,
        })
    },
["WeLoveBerserker!"] = {
        Rewards = {
				Rerolls = 50,
				Units = {
					Kenpachi = 1,
				},
				Items = {
					HolyFragment = 5,
					UniversalFragment = 2,
					PhantomFragment = 2,
					SealedEyepatch = 1,
				},
        },
		LevelRequirement = 10,
        Expiration = os.time({
            year = 2030,
            month = 4,
            day = 27,
            min = 0,
            hour = 17,
            sec = 0,
        })
    },

["TheLastGreatMage!"] = {
        Rewards = {
				Coins = 50_000,
				Gems = 5000,
				Rerolls = 30,
				RelicRerolls = 10,
        },
		LevelRequirement = 15,
        Expiration = os.time({
            year = 2026,
            month = 4,
            day = 20,
            min = 0,
            hour = 16,
            sec = 0,
        })
    },
["TheShinobiWar!"] = {
        Rewards = {
				Coins = 100_000,
				Gems = 5000,
				Rerolls = 50,
				RelicRerolls = 20,
        },
		LevelRequirement = 30,
        Expiration = os.time({
            year = 2026,
            month = 4,
            day = 20,
            min = 0,
            hour = 16,
            sec = 0,
        })
    },
["BetterRates!"] = {
        Rewards = {
				Gems = 5_000,
        },
		LevelRequirement = 5,
        Expiration = os.time({
            year = 2026,
            month = 3,
            day = 23,
            min = 0,
            hour = 16,
            sec = 0,
        })
    },
["Ragnarok!"] = {
        Rewards = {
				Gems = 5_000,
				Coins = 20_000,
				Rerolls = 10,
				StatRerolls = 20,
        },
		
        Expiration = os.time({
            year = 2026,
            month = 3,
            day = 28,
            min = 0,
            hour = 16,
            sec = 0,
        })
    },

["SorryForReallyLongDelay!"] = {
        Rewards = {
				Rerolls = 50,
				Items = {
					SecretEtherealizationShard = 1,
					ExclusiveEtherealizationShard = 1,
				},
        },
		LevelRequirement = 10,
        Expiration = os.time({
            year = 2026,
            month = 3,
            day = 24,
            min = 0,
            hour = 16,
            sec = 0,
        })
    },

["SorryForDelays1.5!"] = {
        Rewards = {
				Rerolls = 100,
        },
        Expiration = os.time({
            year = 2026,
            month = 3,
            day = 21,
            min = 0,
            hour = 16,
            sec = 0,
        })
    },

["FirstRagnarok!"] = {
        Rewards = {
				Rerolls = 50,
				Items = {
					SecretEtherealizationShard = 1,
				},
        },
		LevelRequirement = 15,
        Expiration = os.time({
            year = 2026,
            month = 3,
            day = 28,
            min = 0,
            hour = 16,
            sec = 0,
        })
    },

["Update1.5!"] = {
        Rewards = {
				Gold = 30_000,
				Rerolls = 30,
				Locks = 15,
				Items = {
					MythicEtherealizationShard = 1,
				},
        },
		LevelRequirement = 15,
        Expiration = os.time({
            year = 2026,
            month = 3,
            day = 28,
            min = 0,
            hour = 16,
            sec = 0,
        })
    },
["QOLUpdate1.5!"] = {
        Rewards = {
				Gold = 50_000,
				Rerolls = 50,
				Locks = 5,
				StatRerolls = 20,
        },
		LevelRequirement = 30,
        Expiration = os.time({
            year = 2026,
            month = 3,
            day = 24,
            min = 0,
            hour = 16,
            sec = 0,
        })
    },
["RagnarokisHere!"] = {
        Rewards = {
				Rerolls = 50,
				StatRerolls = 25,
				Locks = 15,	
				Gold = 100_000,
				Gems = 20_000,
				Items = {
					SecretEtherealizationShard = 1,
				},
        },
        CC_Code = true,
        Expiration = os.time({
            year = 2026,
            month = 3,
            day = 26,
            min = 0,
            hour = 12,
            sec = 0,
        })
    },
["SubscribeToUniversalTowerDefense!"] = {
        Rewards = {
				Gems = 5_000,
				Rerolls = 50,
				StatRerolls = 25,
        },
		LevelRequirement = 10,
        Expiration = os.time({
            year = 2026,
            month = 2,
            day = 15,
            min = 0,
            hour = 16,
            sec = 0,
        })
    },

["DevelopmentNews!"] = {
        Rewards = {
				Rerolls = 50,
				Gems = 10_000,
				Items = {
					SecretEtherealizationShard = 1,
					MythicEtherealizationShard = 1,
					ExclusiveEtherealizationShard = 1,
				},
        },
		LevelRequirement = 10,
        Expiration = os.time({
            year = 2026,
            month = 2,
            day = 7,
            min = 0,
            hour = 12,
            sec = 0,
        })
    },
["CC_Feb26"] = {
        Rewards = {
				Rerolls = 200,
        },
        CC_Code = true,
        Expiration = os.time({
            year = 2026,
            month = 3,
            day = 1,
            min = 0,
            hour = 12,
            sec = 0,
        })
    },
["NotPerfect!"] = {
        Rewards = {
				Rerolls = 25,
				Items = {
					SecretEtherealizationShard = 1,
					MythicEtherealizationShard = 1,
					ExclusiveEtherealizationShard = 1,
				},
        },
		LevelRequirement = 5,
        Expiration = os.time({
            year = 2026,
            month = 2,
            day = 5,
            min = 0,
            hour = 16,
            sec = 0,
        })
    },
["PerfectBuffs"] = {
        Rewards = {
				Rerolls = 50,
				StatRerolls = 25,
        },
		LevelRequirement = 15,
        Expiration = os.time({
            year = 2026,
            month = 2,
            day = 5,
            min = 0,
            hour = 16,
            sec = 0,
        })
    },
["Perfectionist"] = {
        Rewards = {
				Rerolls = 100,
				Gems = 10_000,
				Gold = 25_000,
        },
		LevelRequirement = 15,
        Expiration = os.time({
            year = 2026,
            month = 2,
            day = 7,
            min = 0,
            hour = 16,
            sec = 0,
        })
    },

["AndroidGames!"] = {
        Rewards = {
				Rerolls = 25,
				StatRerolls = 50,
				Locks = 25,
        },
		LevelRequirement = 15,
        Expiration = os.time({
            year = 2026,
            month = 2,
            day = 12,
            min = 0,
            hour = 16,
            sec = 0,
        })
    },

["I Have A Wish!"] = {
        Rewards = {
				Gems = 2_500,
				StatRerolls = 50,
				Locks = 25,

				Items = {
					SecretEtherealizationShard = 1,
					MythicEtherealizationShard = 1,
					ExclusiveEtherealizationShard = 1,
					BurningFragment = 2,
					FrozenFragment = 2,
					HolyFragment = 2,
					OceanFragment = 2,
					PetalFragment = 2,
					PhantomFragment = 2,
					SkyFragment = 2,
				},
        },
		
		LevelRequirement = 20,
        Expiration = os.time({
            year = 2026,
            month = 2,
            day = 7,
            min = 0,
            hour = 16,
            sec = 0,
        })
    },

["Update1Reveal!"] = {
        Rewards = {
				Gems = 10000,
				Rerolls = 50,
        },
		LevelRequirement = 20,
        Expiration = os.time({
            year = 2026,
            month = 1,
            day = 25,
            min = 0,
            hour = 16,
            sec = 0,
        })
    },
["PollsUpdate1!"] = {
        Rewards = {
				Rerolls = 50,
        },
		LevelRequirement = 10,
        Expiration = os.time({
            year = 2026,
            month = 1,
            day = 25,
            min = 0,
            hour = 16,
            sec = 0,
        })
    },
["ThankYouForOneMonth!"] = {
        Rewards = {
				Rerolls = 50,
				IceGifts = 15000,
				StatRerolls = 25,
				Locks = 10,
				Gems = 7500,
        },
		LevelRequirement = 25,
        Expiration = os.time({
            year = 2026,
            month = 1,
            day = 16,
            min = 0,
            hour = 16,
            sec = 0,
        })
    },
["WhiteRoseOps"] = {
        Rewards = {
				Rerolls = 50,
				StatRerolls = 25,
				Locks = 10,
        },
		LevelRequirement = 25,
        Expiration = os.time({
            year = 2026,
            month = 1,
            day = 22,
            min = 0,
            hour = 16,
            sec = 0,
        })
    },

["Engage!"] = {
        Rewards = {
				IceGifts = 30000,
        },
		LevelRequirement = 15,
        Expiration = os.time({
            year = 2026,
            month = 1,
            day = 23,
            min = 0,
            hour = 16,
            sec = 0,
        })
    },

["StepUp!"] = {
        Rewards = {
				Gems = 10000,
        },
		LevelRequirement = 20,
        Expiration = os.time({
            year = 2026,
            month = 1,
            day = 22,
            min = 0,
            hour = 16,
            sec = 0,
        })
    },

["SorryForTheDelayGuys!"] = {
        Rewards = {
				Rerolls = 50,
				Gems = 5000,
        },
		LevelRequirement = 5,
        Expiration = os.time({
            year = 2026,
            month = 1,
            day = 19,
            min = 0,
            hour = 16,
            sec = 0,
        })
    },

["WinterPatch26"] = {
        Rewards = {
				Rerolls = 20,
				IceGifts = 5000,
        },
		LevelRequirement = 15,
        Expiration = os.time({
            year = 2026,
            month = 1,
            day = 13,
            min = 0,
            hour = 16,
            sec = 0,
        })
    },
["WinterTIME!"] = {
        Rewards = {
				Rerolls = 25,
				IceGifts = 5000,
				Gold = 1500.
        },
		MusicPresets = {
			["Winter"] = 1,
		},
		LevelRequirement = 25,
        Expiration = os.time({
            year = 2026,
            month = 1,
            day = 24,
            min = 0,
            hour = 16,
            sec = 0,
        })
    },
["WinterUpd"] = {
        Rewards = {
				Rerolls = 25,
				IceGifts = 5000,
        },
		LevelRequirement = 15,
        Expiration = os.time({
            year = 2026,
            month = 1,
            day = 24,
            min = 0,
            hour = 16,
            sec = 0,
        })
    },
["AUniversalWinter!"] = {
        Rewards = {
				StatRerolls = 30,
				Locks = 15,
				IceGifts = 2500,
        },
        Expiration = os.time({
            year = 2026,
            month = 1,
            day = 24,
            min = 0,
            hour = 16,
            sec = 0,
        })
    },
["CC_Jan26"] = {
        Rewards = {
				Rerolls = 200,
        },
        CC_Code = true,
        Expiration = os.time({
            year = 2026,
            month = 2,
            day = 1,
            min = 0,
            hour = 12,
            sec = 0,
        })
    },
["WinterPolls"] = {
        Rewards = {
				Rerolls = 50,
				Locks = 20,
				StatRerolls = 50.
        },
        LevelRequirement = 20,
        Expiration = os.time({
            year = 2026,
            month = 1,
            day = 11,
            min = 0,
            hour = 16,
            sec = 0,
        })
    },
["ILoveWinter!"] = {
        Rewards = {
				Rerolls = 100,
        },
        LevelRequirement = 25,
        Expiration = os.time({
            year = 2026,
            month = 1,
            day = 15,
            min = 0,
            hour = 16,
            sec = 0,
        })
    },
["SmallGift"] = {
        Rewards = {
                Rerolls = 10,
                Gems = 1000,
        },
        Expiration = os.time({
            year = 2026,
            month = 1,
            day = 5,
            min = 0,
            hour = 12,
            sec = 0,
        })
    },

["Update 0.5"] = {
        Rewards = {
                Rerolls = 25,
                Gems = 5000,
        },
        LevelRequirement = 5,
        Expiration = os.time({
            year = 2026,
            month = 1,
            day = 10,
            min = 0,
            hour = 12,
            sec = 0,
        })
    },
["PeroxideUpd!"] = {
        Rewards = {
                Rerolls = 25,
                Gems = 2500,
                Gold = 10000,
        },
        Items = {
			BurningFragment = 1,
			FrozenFragment = 1,
			HolyFragment = 1,
			OceanFragment = 1,
			PetalFragment = 1,
			PhantomFragment = 1,
			SkyFragment = 1,
		},
        LevelRequirement = 15,
        Expiration = os.time({
            year = 2026,
            month = 1,
            day = 6,
            min = 0,
            hour = 12,
            sec = 0,
        })
    },

["NewYear26!"] = {
        Rewards = {
                Rerolls = 50,
                StatRerolls = 30,
                Locks = 15,
        },
        LevelRequirement = 50,
        Expiration = os.time({
            year = 2026,
            month = 1,
            day = 10,
            min = 0,
            hour = 12,
            sec = 0,
        })
    },

["InterestedIn0.5!"] = {
        Rewards = {
                Rerolls = 25,
        },
        LevelRequirement = 15,
        Expiration = os.time({
            year = 2026,
            month = 1,
            day = 5,
            min = 0,
            hour = 12,
            sec = 0,
        })
    },

["ILoveUTD!"] = {
        Rewards = {
                Rerolls = 50,
				Gems = 2000,
        },
        LevelRequirement = 25,
        Expiration = os.time({
            year = 2026,
            month = 1,
            day = 5,
            min = 0,
            hour = 12,
            sec = 0,
        })
    },
["WinterIsComing!"] = {
        Rewards = {
                SpiritSouls = 250,
				Gems = 3000,
				Rerolls = 15,
        },
        LevelRequirement = 20,
        Expiration = os.time({
            year = 2026,
            month = 1,
            day = 8,
            min = 0,
            hour = 12,
            sec = 0,
        })
    },
}
