return {
["WeLoveUTDZ2!"] = {
        Rewards = {
				Relics = {
					["KenpachiSword"] = {
						Type = "Accessory",
						Rarirty = "Exclusive",
						Amount = 1,
					},
				}
        },
		LevelRequirement = 5,
        Expiration = os.time({
            year = 2126,
            month = 7,
            day = 13,
            min = 0,
            hour = 10,
            sec = 0,
        })
    }, 

["WeLoveUTDZ!"] = {
        Rewards = {
				Items = {
					["MythicEtherealizationShard"] = 12,

					["MageStaff"] = 1,

					["PetalFragment"] = 6,
					["PhantomFragment"] = 4,
					["UniversalFragment"] = 2,					
				},
				Units = {
					["Fern"] = 1,
					["Kenpachi:evolved"] = 1,
				},
        },
		LevelRequirement = 5,
        Expiration = os.time({
            year = 2126,
            month = 7,
            day = 12,
            min = 0,
            hour = 10,
            sec = 0,
        })
    }, 

["UTDZApologyForBugs!"] = {
        Rewards = {
				Rerolls = 1500,
				Items = {
					["BoundlessOrb"] = 1,
				}
        },
		LevelRequirement = 20,
        Expiration = os.time({
            year = 2026,
            month = 7,
            day = 13,
            min = 0,
            hour = 10,
            sec = 0,
        })
    }, 

["SrryForWhoopsie!"] = {
        Rewards = {
				Items = {
					["Ruler__Ticket"] = 1,
				}
        },
		LevelRequirement = 30,
        Expiration = os.time({
            year = 2026,
            month = 7,
            day = 12,
            min = 0,
            hour = 10,
            sec = 0,
        })
    }, 

["ReapersVsHollowDestroyers"] = {
        Rewards = {
				Gems = 10_000,
				Rerolls = 50,
        },
		LevelRequirement = 20,
        Expiration = os.time({
            year = 2026,
            month = 7,
            day = 16,
            min = 0,
            hour = 10,
            sec = 0,
        })
    }, 

["SpectacularSpider!"] = {
        Rewards = {
				UniversalGemsSeason1 = 100_000,
				Rerolls = 50,
        },
		LevelRequirement = 30,
        Expiration = os.time({
            year = 2026,
            month = 7,
            day = 12,
            min = 0,
            hour = 10,
            sec = 0,
        })
    }, 

["TheGuyFromSmash!"] = {
        Rewards = {
				UniversalGemsSeason1P2 = 100_000,
				Rerolls = 50,
        },
		LevelRequirement = 35,
        Expiration = os.time({
            year = 2026,
            month = 7,
            day = 11,
            min = 0,
            hour = 10,
            sec = 0,
        })
    }, 
["Summer2026!"] = {
        Rewards = {
				Rerolls = 50,
				SummerCurrency = 10_000
        },
		LevelRequirement = 35,
        Expiration = os.time({
            year = 2026,
            month = 7,
            day = 11,
            min = 0,
            hour = 10,
            sec = 0,
        })
    }, 
["UTDPhase3!"] = {
        Rewards = {
				UniversalGemsSeason1 = 100_000,
				Rerolls = 150,
				Units = {
					["Grimmjow"] = 1,
				},
				Items = {
					["Hollow Skull Jaw"] = 1,
					UniversalFragment = 2,
					PetalFragment = 8,	
					OceanFragment = 6,	
				},
        },
		LevelRequirement = 20,
        Expiration = os.time({
            year = 2026,
            month = 7,
            day = 8,
            min = 0,
            hour = 10,
            sec = 0,
        })
    }, 

["UTDXRulerIncident!"] = {
        Rewards = {
				Items = {
					RulerTicket = 2,
				},
        },
		LevelRequirement = 30,
        Expiration = os.time({
            year = 2026,
            month = 7,
            day = 1,
            min = 0,
            hour = 10,
            sec = 0,
        })
    }, 

["UniversalTowerDefenseZ!"] = {
        Rewards = {
				Rerolls = 250,
				UniversalGemsSeason1P2 = 100_000,
				Units = {
					["Vergil"] = 1,
				},
				Items = {
					VergilSword = 1,
					OceanFragment = 10,
					SkyFragment = 8,
					UniversalFragment = 3,
				},
        },
		LevelRequirement = 0,
        Expiration = os.time({
            year = 2026,
            month = 6,
            day = 30,
            min = 0,
            hour = 10,
            sec = 0,
        })
    }, 
["UniversalDelayDefense!"] = {
        Rewards = {
				Rerolls = 500,
				Gems = 25_000,
				UniversalGemsSeason1P2 = 100_000,
				UniversalGemsSeason1 = 100_000,
				Units = {
					["Dante"] = 1,
				},
				Items = {
					DanteSword = 1,
					BurningFragment = 10,
					PetalFragment = 8,
					UniversalFragment = 3,
					FlamesAndWavesCapsule = 50,
				},
				Coins = 50_000,
        },
		LevelRequirement = 25,
        Expiration = os.time({
            year = 2026,
            month = 6,
            day = 29,
            min = 0,
            hour = 10,
            sec = 0,
        })
    }, 
["200KInterestedSouls!"] = {
        Rewards = {
				Rerolls = 200,
				Gems = 20_000,
				UniversalGemsSeason1P2 = 50_000,
        },
		LevelRequirement = 15,
        Expiration = os.time({
            year = 2026,
            month = 6,
            day = 20,
            min = 0,
            hour = 10,
            sec = 0,
        })
    },
["ArrancarSupremacy!"] = {
        Rewards = {
				Rerolls = 100,
				UniversalGemsSeason1P2 = 100_000,
		},
		LevelRequirement = 15,
        Expiration = os.time({
            year = 2026,
            month = 6,
            day = 21,
            min = 0,
            hour = 20,
            sec = 0,
        })
    },
["ExclusiveRelics!"] = {
        Rewards = {
				Rerolls = 100,
				RelicRerolls = 30,
				Items = {
					MaximumChamber = 1,
				},
		},
		LevelRequirement = 15,
        Expiration = os.time({
            year = 2026,
            month = 6,
            day = 20,
            min = 0,
            hour = 20,
            sec = 0,
        })
    },

["DropRateFixes!"] = {
        Rewards = {
				Rerolls = 100,
				Items = {
					GohanSword = 2,
					GohanGlasses = 1,
					FlamesAndWavesCapsule = 15,
				},
		},
		LevelRequirement = 0,
        Expiration = os.time({
            year = 2026,
            month = 6,
            day = 20,
            min = 0,
            hour = 20,
            sec = 0,
        })
    },

["3.0Part2.5Update!"] = {
        Rewards = {
				Rerolls = 50,
				Gems = 5_000,
				RelicRerolls = 25,
				Coins = 30_000,
		},
		LevelRequirement = 0,
        Expiration = os.time({
            year = 2026,
            month = 6,
            day = 20,
            min = 0,
            hour = 20,
            sec = 0,
        })
    },

["TheBeast!"] = {
        Rewards = {
				Rerolls = 100,
				Gems = 10_000,
				RelicRerolls = 25,
				Locks = 20,
				StatRerolls = 20,
				Coins = 100_000,
		},
		LevelRequirement = 30,
        Expiration = os.time({
            year = 2026,
            month = 6,
            day = 20,
            min = 0,
            hour = 20,
            sec = 0,
        })
    },

["BeastDelay!"] = {
        Rewards = {
				Rerolls = 150,
				UniversalGemsSeason1P2 = 50_000,
				UniversalGemsSeason1 = 100_000,
				Locks = 20,
				StatRerolls = 50,
				Coins = 100_000,
		},
		LevelRequirement = 20,
        Expiration = os.time({
            year = 2026,
            month = 6,
            day = 20,
            min = 0,
            hour = 20,
            sec = 0,
        })
    },

["CC_UniversalFestFinale"] = {
        Rewards = {
				Items = {
					BoundlessOrb = 1,
					FlamesAndWavesCapsule = 50,
				},
        },
        CC_Code = true,
        Expiration = os.time({
            year = 2026,
            month = 6,
            day = 22,
            min = 0,
            hour = 16,
            sec = 0,
        })
    },

["DBSLagFixes!"] = {
        Rewards = {
				Rerolls = 100,
				Gems = 25_000,
				UniversalGemsSeason1P2 = 50_000,
				UniversalGemsSeason1 = 50_000,
				Units = {
					["Nelliel:shiny:evolved"] = 1,
				},
		},
		LevelRequirement = 0,
        Expiration = os.time({
            year = 2026,
            month = 6,
            day = 11,
            min = 0,
            hour = 20,
            sec = 0,
        })
    },
}
