return {
["RELEASE!"] = {
        Rewards = {
                Gems = 400,
        },

        Expiration = os.time({
            year = 2025,
            month = 12,
            day = 21,
            min = 0,
            hour = 18,
            sec = 0,
        })
    },

["UNRIVALED!"] = {
        Rewards = {
                Gems = 200,
                Rerolls = 5,
        },

        Expiration = os.time({
            year = 2025,
            month = 12,
            day = 24,
            min = 0,
            hour = 12,
            sec = 0,
        })
    },

["Universal!"] = {
    Rewards = {
                Gems = 450,
                Rerolls = 15,
        },
       
        Expiration = os.time({
            year = 2025,
            month = 12,
            day = 22,
            min = 0,
            hour = 20,
            sec = 0,
        })
    },

["NumberOne!"] = {
    Rewards = {
                Gems = 500,
                Rerolls = 15,
        },
        Expiration = os.time({
            year = 2025,
            month = 12,
            day = 22,
            min = 0,
            hour = 20,
            sec = 0,
        })
    },

["Mainstream!"] = {
    Rewards = {
                Gems = 450,
                Rerolls = 15,
        },
        Expiration = os.time({
            year = 2025,
            month = 12,
            day = 25,
            min = 0,
            hour = 20,
            sec = 0,
        })
    },
["ThankYouUTD!"] = {
    Rewards = {
                Gems = 400,
                Rerolls = 5,
        },
        Expiration = os.time({
            year = 2025,
            month = 12,
            day = 22,
            min = 0,
            hour = 20,
            sec = 0,
        })
    },

["75kLikes!"] = {
    Rewards = {
                Gems = 400,
                Rerolls = 10,
        },
        Expiration = os.time({
            year = 2025,
            month = 12,
            day = 22,
            min = 0,
            hour = 20,
            sec = 0,
        })
    },

["ThousandsOfCodes!"] = {
    Rewards = {
                Gems = 800,
                Rerolls = 15,
        },
        LevelRequirement = 5,
        Expiration = os.time({
            year = 2025,
            month = 12,
            day = 21,
            min = 0,
            hour = 20,
            sec = 0,
        })
    },

["SixSeven!"] = {
    Rewards = {
                Rerolls = 67,
        },
        LevelRequirement = 15,
        Expiration = os.time({
            year = 2025,
            month = 12,
            day = 23,
            min = 0,
            hour = 12,
            sec = 0,
        })
    },
["MaxedOut!"] = {
    Rewards = {
                 Gems = 600,
                Rerolls = 10,
        },
        LevelRequirement = 5,
        Expiration = os.time({
            year = 2025,
            month = 12,
            day = 24,
            min = 0,
            hour = 12,
            sec = 0,
        })
    },

["ThankYou100k"] = {
    Rewards = {
                Rerolls = 100,
        },
        LevelRequirement = 50,
        Expiration = os.time({
            year = 2025,
            month = 12,
            day = 24,
            min = 0,
            hour = 12,
            sec = 0,
        })
    },

["HereyougoEA!"] = {
    Rewards = {
                 Gems = 2000,
                Rerolls = 20,
                Locks = 5,
        },
        RequiresEA = true,
        Expiration = os.time({
            year = 2025,
            month = 12,
            day = 24,
            min = 0,
            hour = 12,
            sec = 0,
        })
    },
["UnrivaledIsAlive"] = {
        Rewards = {
                Gems = 800,
                Rerolls = 20,
        },
         LevelRequirement = 15,
        Expiration = os.time({
            year = 2025,
            month = 12,
            day = 23,
            min = 0,
            hour = 18,
            sec = 0,
        })
    },

["ThankYouFor150k"] = {
        Rewards = {
                Gems = 1500,
                Rerolls = 50,
        },
         LevelRequirement = 50,
        Expiration = os.time({
            year = 2025,
            month = 12,
            day = 23,
            min = 0,
            hour = 18,
            sec = 0,
        })
    },

["ThankYou30M"] = {
        Rewards = {
                Gems = 500,
                Rerolls = 15,
        },
         LevelRequirement = 15,
        Expiration = os.time({
            year = 2025,
            month = 12,
            day = 26,
            min = 0,
            hour = 18,
            sec = 0,
        })
    },

["YT10k!"] = {
        Rewards = {
                Gems = 2000,
        },
        Expiration = os.time({
            year = 2025,
            month = 12,
            day = 26,
            min = 0,
            hour = 18,
            sec = 0,
        })
    },
["MerryChristmas"] = {
        Rewards = {
                Rerolls = 100,
                StatRerolls = 50,
                Locks = 10,
        },
        Expiration = os.time({
            year = 2025,
            month = 12,
            day = 28,
            min = 0,
            hour = 12,
            sec = 0,
        })
    },

["MaintenanceTomorrow_0.5!"] = {
        Rewards = {
                Rerolls = 50,
        },
        LevelRequirement = 15,
        Expiration = os.time({
            year = 2026,
            month = 1,
            day = 3,
            min = 0,
            hour = 12,
            sec = 0,
        })
    },

["SmallGift"] = {
        Rewards = {
                Rerolls = 10,
                Gems = 1000,
        },
        Expiration = os.time({
            year = 2026,
            month = 1,
            day = 5,
            min = 0,
            hour = 12,
            sec = 0,
        })
    },

["Update 0.5"] = {
        Rewards = {
                Rerolls = 25,
                Gems = 5000,
        },
        LevelRequirement = 5,
        Expiration = os.time({
            year = 2026,
            month = 1,
            day = 10,
            min = 0,
            hour = 12,
            sec = 0,
        })
    },
["PeroxideUpd!"] = {
        Rewards = {
                Rerolls = 25,
                Gems = 2500,
                Gold = 10000,
        },
        Items = {
			BurningFragment = 1,
			FrozenFragment = 1,
			HolyFragment = 1,
			OceanFragment = 1,
			PetalFragment = 1,
			PhantomFragment = 1,
			SkyFragment = 1,
		},
        LevelRequirement = 15,
        Expiration = os.time({
            year = 2026,
            month = 1,
            day = 6,
            min = 0,
            hour = 12,
            sec = 0,
        })
    },

["Sorry4Delay!"] = {
        Rewards = {
                Rerolls = 50,
                StatRerolls = 30,
                Locks = 15,
        },
        LevelRequirement = 50,
        Expiration = os.time({
            year = 2026,
            month = 1,
            day = 10,
            min = 0,
            hour = 12,
            sec = 0,
        })
    },
}
